### ISSUE TITLE
Need to add ignore prefix

### ISSUE THREAD

**Issue by VadimZhiltsov** [jareware/css-ns#1]
Great idea for a library! I uses it with big pleasure. 
I think it could be improved. On my project we lack for a ignore prefix, which would be replaced by library. Let me illustrate what I mean:
Let we have a React Component:
```
import R from 'react'
import { createCssNs } from 'css-ns'
const { React } = createCssNs({
   'Example',
    React: R,
    glue: '-',
    globalPrefix: '~'
  })

class Example extends React.Component {
  render () {
    return (
      <div className='this'>
		<div className='title'></div>
                <div className='~global-class-name'
      </div>)
  }
}
```

And this would transforms to:
```
<div className='Example'>
        <div className='Example-title'></div>
        <div className='global-class-name'
</div>
```

It would be very helpful. Now I don't see any workaround except create a prefix for all non-components classes

**Comment by jareware** [comment]
Hmm, I've actually had a very similar improvement in mind! Especially if this means both `include` and `exclude` options could just be dropped.

When I have a bit of extra time I'll see how this works out and report back, thanks!
