### ISSUE TITLE
installation with yarn fails

### ISSUE THREAD

**Issue by brbcoding** [jareware/css-ns#7]
## Expected Behavior
`yarn add css-ns` should successfully install `css-ns` with latest versions of node

## Actual Behavior
```
error css-ns@1.2.1: The engine "node" is incompatible with this module. Expected version ">=9.3.0 <10". Got "10.7.0"
error Found incompatible module
```

## Steps to Reproduce the Problem 
1. Initialize npm (`npm init -y`)
2. `yarn add css-ns` while using any version of node < 9.3 or >= 10

## Specifications
  - Version: 1.2.1
  - Platform: OSX

## Notes
It looks like [this commit](https://github.com/jareware/css-ns/commit/b7cb3453c51fb70abe2012e00ec9d5324321774c) fixed the issue but downloads from npm still show `"node": ">=9.3.0 <10",` in `package.json`. Maybe the latest just didn't get pushed to npm?
```
  "engines": {
    "node": ">=9.3.0 <10",
    "npm": ">=5.5.1 <6"
  },
```

**Comment by jareware** [comment]
Hey, thanks for the report, and sorry for not getting back to it sooner!

Indeed it looks like a new release wasn't rolled out for this change. I'll make sure to make one.

**Comment by jareware** [comment]
Done!
